name: Deploy VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to docker hub
        run : echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/keep-this-client:latest .

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/keep-this-client:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/keep-this-client:latest
            docker stop keep-this-client || true
            docker rm keep-this-client || true
            docker run -d --name keep-this-client -p 80:80 ${{ secrets.DOCKER_USERNAME }}/keep-this-client:latest
